### ISSUE TITLE
Add "Save to library /add to playlist" buttons next to Tracks

### ISSUE THREAD

**Issue by foco76** [jeroentvb/spicetify-power-bar#31]
It would be great to have Save to library and add to playlist buttons right side to the track(songs) because if else we need to click songs one by one and add it to library or playlists !
Thank You!

**Comment by jeroentvb** [comment]
A save to library button could be added, but I don't really see why you would want to do that from the power bar. It would make much more sense to have such a button next to the now playing track (where it already is).

As for add to playlist, that would add much more complexity, and in my opinion clutter, to the interface, because after pressing such button you'd have to select the playlist to add to. It wouldn't be much faster than using spotify's built in search. The power bar is meant as a quick search and to quickly navigate to an item or add it to the queue.
