### ISSUE TITLE
Change the background color of search

### ISSUE THREAD

**Issue by CharlieS1103** [jeroentvb/spicetify-power-bar#7]
Shadow seems like a weird var to use as many themes don't have a shadow (therefore shadow color will be set to the same as main color, causing search to look odd). Some ideas of what to use instead include misc, or notification

**Comment by jeroentvb** [comment]
The shadow var is only used for the box shadow and borders. Borders could probably be changed to main or player.

Misc as a background-color looks kind of ugly imo, but the contrast it provides is good. The notification color may work better. Although I think colors should be used for the things they are named for, I'll give the notification color as background a go.

**Comment by jeroentvb** [comment]
I think I may have found a nice background. Took some inspiration from the modal used for the experimental features modal. Using `--spice-tab-active` and a dimmed background outside the search window you get a contrast that works, but also fits with spotify's design and color scheme. It should also fit in a theme because of the use of spicetify variables.

![Schermafbeelding 2022-01-30 om 22 19 50](https://user-images.githubusercontent.com/36192730/151718443-ce9d3e6e-8272-4fae-bff2-05d4ad1b69d7.png)

Also tried the notification color as background, but imo it's a bit too much. It could be included as kind of custom theme for the power bar. Obviously needs some more tweaking than just changing the background color. I'm open to PR's for that as I'm not interested in building that myself (I'd like to have it feel as close as possible to being part of spotify in stock config).

![Schermafbeelding 2022-01-30 om 22 22 51](https://user-images.githubusercontent.com/36192730/151718446-beffc7f5-b97b-4361-a179-78af602fa398.png)

**Comment by jeroentvb** [comment]
@CharlieS1103 what do you think of the current background?
